name: Community Pool Spend Proposal
description: Propose that the Community Pool is spent
title: "[Community Pool Spend]: "
labels: ["Community Pool", "Proposal"]
assignees:
  - Alex Tweeddale
body:
- type: textarea
  id: summary
  attributes:
    label: Summary
    description: A short (~150 word) description of the Proposal you want to make. 
                 Provide a simplified and layman-accessible explanation of the Proposal in plain English to have the best chance of gaining community interest and having it accepted.
  validations:
    required: true
- type: textarea
  id: rationale
  attributes:
    label: Summary
    description: A longer <500 description of what you want the community pool to be spent on, making direct references to where you want to make changes from, using links.
    placeholder: I want to donate the community pool to X initiative because they support X.
  validations:
    required: false
- type: input
  id: link
  attributes:
    label: Proposed Community Spend
    description: Please link to the initiatve, organisation, or other entity which it is proposed to donate the Community Pool to.
    placeholder: (Insert link)
    value: 
  validations:
    required: false
- type: input
  id: value
  attributes:
    label: Proposed Spend Value
    description: Please enter the amount of $CHEQ you propose to be donated to the recipient.
    placeholder: 100,000 $CHEQ
    value: 
  validations:
    required: true
- type: input
  id: new
  attributes:
    label: New Parameter Value
    description: What is the parameter value that you want to change to?
    placeholder: $10,000 CHEQ
    value: 
  validations:
    required: true
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/cheqd/.github/blob/main/CODE_OF_CONDUCT.md)
    options:
    - label: I agree to follow this project's Code of Conduct
      required: true
