blank_issues_enabled: false
contact_links:
  - name: Community Slack
    url: http://cheqd.link/join-cheqd-slack
    about: Community Slack for Q&A and discussions
  - name: Technical Documentation
    url: https://docs.cheqd.io
    about: Technical Documentation for cheqd projects
  - name: Governance Forum
    url: https://commonwealth.im/cheqd
    about: System status reporting tool for cheqd services
  - name: System Status
    url: https://status.cheqd.net
    about: System status reporting tool for cheqd services