name: Markdown quality control checks

on: [push]

jobs:
  check_links:
    name: Markdown - Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          github_token: ${{ secrets.GH_TOKEN }}
          persist-credentials: false
      - name: Check if Markdown links are valid
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with: 
          config-file: '.github/workflows/mlc_config.json'
          folder-path: "."

  lint-check:
    name: Markdown - Linting Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check if Markdown is formatted correctly
      uses: avto-dev/markdown-lint@v1
      with:
        rules: '.github/workflows/markdown-rules/changelog.js'
        config: '.github/workflows/markdown-rules/changelog.yml'
        args: '.'
        fix: true
